name: Python Application CI

on:
  push:
    branches: [ main, logging ]
  pull_request:
    branches: [ main, logging ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv
          pip install pylint mypy

      - name: Run linting and type-checking
        run: |
          pylint --rcfile=.pylintrc .
          mypy .
      
      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
